-- Add search_queries column to segments table for Pipeline B
-- Stores the visual search queries generated by Pipeline A

ALTER TABLE segments ADD COLUMN search_queries TEXT[];
ALTER TABLE segments ADD COLUMN fallback_query TEXT;

-- Add index for efficient querying
CREATE INDEX segments_search_queries_idx ON segments USING GIN (search_queries);
